services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo_network
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh admin -u admin -p pass --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "8081:8081"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - mongo_network
    restart: always

  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: node-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - mongo_network
    restart: always

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "80:80"
    networks:
      - mongo_network
    depends_on:
      - backend
    restart: always

volumes:
  mongo_data:

networks:
  mongo_network:
    driver: bridge
